### ISSUE TITLE
SuiteScript 2.0

### ISSUE THREAD

**Issue by DempseyWilliams** [3EN-Cloud/autocomplete-netsuite#1]
Are there any plans to expand this to support SuiteScript 2.0?

**Comment by matthewwilson** [comment]
Hi @DempseyWilliams ,

Yes we plan to add full SuiteScript 2.0 support. We don't have a planned release date yet. 

Thanks
Matthew

**Comment by matthewwilson** [comment]
@DempseyWilliams initial SuiteScript 2.0 was merged and deployed today, you can update the package in atom and try it out!

**Comment by DempseyWilliams** [comment]
Excellent!
