### ISSUE TITLE
Autocomplete for 2.0

### ISSUE THREAD

**Issue by Rusty-Vermithrax** [3EN-Cloud/autocomplete-netsuite#3]
Hi, I am not able to make the autocomplete for SuiteScript 2.0.  When I use one of the modules like search, it does not show the options automatically.

Also is it possible to change the value of the suitecomment? Or have one for 1.0 and another for 2.0?

Thanks!

**Comment by matthewwilson** [comment]
Hi @Rusty-Vermithrax 

Do you have any example code that wasn't autocompleting for you?

What format would you like for a 2.0 comment?

**Comment by Rusty-Vermithrax** [comment]
Hi @matthewcodes,

Just asking if it is possible to specify format in cases where the company imposes a specific header comment on the scripts.

Below is the sample code

```
/**
 * @NApiVersion 2.x
 * @NScriptType Suitelet
 */
define(['N/ui/serverWidget', 'N/runtime', 'N/search'],
     function(ui, runtime, search) {
          return {
               onRequest: function(context) {
                    var form = ui.createForm({
                         title: 'Select Search To Run'
                    });
               }
          };
     });
```

When I type ui., it does not list the methods for the 'N/ui/serverWidget' module.

**Comment by matthewwilson** [comment]
Thanks @Rusty-Vermithrax,

For the script header, I think we might remove it from this project and add it to this one instead - https://github.com/3EN-Cloud/NetSuite-Atom-Snippet. That would allow you to customise it to whatever format is imposed upon you!

Currently we don't support autocomplete for 2.0 that is able to determine the types of objects passed into a callback function. It is something we want to implement in the future. I will keep this issue open and update on any progress we make. 

Feel free to fork this repo and start implementing it yourself!!

**Comment by matthewwilson** [comment]
Some new 2.0 features added to the 1.4.0 release:

- Support for log and util global objects.
- Support for define and require global functions.
- Support for all `record.Type` enum values. e.g. `record.Type.EMPLOYEE`

**Comment by Rusty-Vermithrax** [comment]
Can you give me a sample code where the autocomplete for 2.0 will work? 

Thanks!

**Comment by matthewwilson** [comment]
From the readme:

Support for all member functions.
Support for `log` and `util` global objects.
Support for `define` and `require` global functions.
Support for all `record.Type` enum values. e.g. `record.Type.EMPLOYEE`

**Comment by matthewwilson** [comment]
I have discovered that there are some method calls and object missing from SuiteScript 2.0 autocomplete. I will update here once we add the missing items.

**Comment by TenteMarrero** [comment]
@matthewcodes thanks for the package. I weekly code NetSuite SuiteScript. I would like to contribute in adding more NS 2.0 native modules (record, search, ui, and so on), please contact me if interested.

**Comment by matthewwilson** [comment]
@TenteMarrero yes no problem, fork the repo and create a PR when you are finished. Thanks for helping!

**Comment by TenteMarrero** [comment]
Thanks @matthewcodes ! I will start with one module to see how it goes.
