### ISSUE TITLE
SS2.0 method parameters should follow API definition

### ISSUE THREAD

**Issue by owieboy** [3EN-Cloud/autocomplete-netsuite#4]
Hi,

I started writing SuiteScript a few days ago and this Atom extension is a big help. 
I noticed though that the autocomplete feature for 2.0 method parameters do not follow the API definition downloadable from Netsuite.

For example, given the API definition:

/**
 * Load an existing nlobjRecord from the database based on provided type, id
 *
 * @governance 10 units for transactions, 2 for custom records, 5 for all other records
 *
 * @param {Object} options
 * @param {string} options.type record type
 * @param {number|string} options.id record id
 * @param {boolean} [options.isDynamic=false] record is dynamic
 * @param {Object} [options.defaultValues={}] record default values
 * @return {Record}
 *
 * @throws {SuiteScriptError} SSS_MISSING_REQD_ARGUMENT if options.type or options.id is missing
 *
 * @since 2015.2
 */
function loadRecord() {} 

When using autocomplete for record.load, I get this

![atom-autocomplete-current-ss2](https://user-images.githubusercontent.com/7962021/29545280-f9c4878e-871f-11e7-8766-08d3082a3d8b.PNG)

Shouldn't it be like this one?

![atom-autocomplete-ss2](https://user-images.githubusercontent.com/7962021/29545295-102bff16-8720-11e7-92d2-09c4661dc7ef.PNG)

**Comment by owieboy** [comment]
I'd be happy to work and submit a PR for this. Right now, I could not find a way to export the API definitions from JSDOC to JSON similar to what's used in `netsuite-api2.json`. Can anyone share how they did it? Thanks!

**Comment by matthewwilson** [comment]
Hi @owieboy,

Yes I think some of the SS2.0 method definitions are incorrect. I'm not sure how the netsuite-api2.json was generated, I've a feeling it was done manually. (They were added as part of another PR https://github.com/3EN-Cloud/autocomplete-netsuite/pull/2)

Any help you can offer for this would be appreciated. This plugin is used heavily in our organisation but we are all a bit busy on other projects ATM. We will be focusing on this in the future though.

Thanks
Matthew

**Comment by owieboy** [comment]
Noted on that @matthewcodes. Hope I can find a way to convert the JSDOC to the same JSON format used here.

**Comment by matthewwilson** [comment]
@owieboy If it's not possible, we could move the SS2.0 code to use a different format.

**Comment by r-long** [comment]
@owieboy a script was used to parse the JSDOC into JSON it missed some cases.

**Comment by owieboy** [comment]
Hi guys, I was able to write a script to parse JSDOC of SS2.0 and to export a newer version of netsuite-api2.json. I will be submitting a pull request containing the updated netsuite-api2.json file.

**Comment by matthewwilson** [comment]
thanks @owieboy, I have merged your PR and deployed, its available in version 1.5.0
